<?php
// -------------------------------------------------------------------
// This file was automatically generated by the LangBuilder.php script
// Date of creation: 2012/05/01 13:19:25
// -------------------------------------------------------------------
global $lang;


// Output for class or file: ShopAdmin
$lang['en_US']['ShopAdmin']['NOTPARTOFTHESITETREE'] = 
	'Not part of the site tree';
$lang['en_US']['ShopAdmin']['VIEW'] = 
	'View Page';
$lang['en_US']['ShopAdmin']['VIEWLIVE'] = 
	'Live Site';
$lang['en_US']['ShopAdmin']['VIEWDRAFT'] = 
	'Draft Site';
$lang['en_US']['ShopAdmin']['BACKTOLIST'] = 
	'Back to list view';

// Output for class or file: ModelAdmin
$lang['en_US']['ModelAdmin']['PUBLISHED'] = 
	'Published';
$lang['en_US']['ModelAdmin']['UNPUBLISHED'] = 
	'Unpublished';
$lang['en_US']['ModelAdmin']['ROLLEDBACK'] = 
	'Rolled back version';
$lang['en_US']['ModelAdmin']['DELETED'] = 
	'Deleted';
$lang['en_US']['ModelAdmin']['SAVED'] = 
	'Saved';
$lang['en_US']['ModelAdmin']['DELETEDFROMLIVE'] = 
	'Deleted';
$lang['en_US']['ModelAdmin']['SEARCHFOR'] = 
	'Search for:';

// Output for class or file: ShopSettings
$lang['en_US']['ShopSettings']['LICENSEKEY'] = 
	'License Key';
$lang['en_US']['ShopSettings']['FROM'] = 
	'From';
$lang['en_US']['ShopSettings']['TO'] = 
	'To';
$lang['en_US']['ShopSettings']['RECEIPT_TO'] = 
	'Sent to customer';
$lang['en_US']['ShopSettings']['SUBJECT_LINE'] = 
	'Subject line';
$lang['en_US']['ShopSettings']['MESSAGE'] = 
	'Message (order details are included in the email)';
$lang['en_US']['ShopSettings']['SIGNATURE'] = 
	'Signature';
$lang['en_US']['ShopSettings']['NOTIFICATION_FROM'] = 
	'Customer email address';
$lang['en_US']['ShopSettings']['SWIPESTRIPELICENSEWARNING'] = 
	'<p class="message warning">
					 Warning: You have SwipeStripe installed without a license key. 
					 Please <a href="http://swipestripe.com" target="_blank">purchase a license key here</a> before this site goes live.
				</p>';

// Output for class or file: AccountPage
$lang['en_US']['AccountPage']['YOUMUSTBELOGGED'] = 
	'You must be logged in to view this page.';
$lang['en_US']['AccountPage']['YOUCANNOTVIEWORDERS'] = 
	'You cannot view orders that do not belong to you.';
$lang['en_US']['AccountPage']['NOORDERTOTHISID'] = 
	'You do not have any order corresponding to this ID.';
$lang['en_US']['AccountPage']['DATE'] = 
	'Date';
$lang['en_US']['AccountPage']['SHIPTO'] = 
	'Ship to';
$lang['en_US']['AccountPage']['TOTAL'] = 
	'Total';
$lang['en_US']['AccountPage']['STATUS'] = 
	'Status';
$lang['en_US']['AccountPage']['VIEWTHISORDER'] = 
	'View this order';

// Output for class or file: CartPage
$lang['en_US']['CartPage']['UPDATECART'] = 
	'Update Cart';
$lang['en_US']['CartPage']['GOTOCHECKOUT'] = 
	'Go To Checkout';

// Output for class or file: CheckoutPage
$lang['en_US']['CheckoutPage']['PROCEEDTOPAY'] = 
	'Proceed to pay';
$lang['en_US']['CheckoutPage']['FIRSTNAME'] = 
	'First Name';
$lang['en_US']['CheckoutPage']['PLEASEENTERYOURFIRSTNAME'] = 
	'Please enter your first name.';
$lang['en_US']['CheckoutPage']['SURNAME'] = 
	'Surname';
$lang['en_US']['CheckoutPage']['PLEASEENTERYOURSURNAME'] = 
	'Please enter your surname.';
$lang['en_US']['CheckoutPage']['ADDRESS1'] = 
	'Address 1';
$lang['en_US']['CheckoutPage']['PLEASEENTERYOURADDRESS'] = 
	'Please enter your address.';
$lang['en_US']['CheckoutPage']['CITY'] = 
	'City';
$lang['en_US']['CheckoutPage']['PLEASEENTERYOURCITY'] = 
	'Please enter your city';
$lang['en_US']['CheckoutPage']['COUNTRY'] = 
	'Country';
$lang['en_US']['CheckoutPage']['PLEASEENTERYOURCOUNTRY'] = 
	'Please enter your country.';
$lang['en_US']['CheckoutPage']['BILLINGADDRESS'] = 
	'Billing Address';
$lang['en_US']['CheckoutPage']['COMPANY'] = 
	'Company';
$lang['en_US']['CheckoutPage']['ADDRESS2'] = 
	'Address 2';
$lang['en_US']['CheckoutPage']['POSTALCODE'] = 
	'Postal Code';
$lang['en_US']['CheckoutPage']['STATE'] = 
	'State';
$lang['en_US']['CheckoutPage']['PLEASEENTERAFIRSTNAME'] = 
	'Please enter a first name.';
$lang['en_US']['CheckoutPage']['PLEASEENTERASURNAME'] = 
	'Please enter a surname.';
$lang['en_US']['CheckoutPage']['PLEASEENTERANADDRESS'] = 
	'Please enter an address.';
$lang['en_US']['CheckoutPage']['PLEASEENTERACITY'] = 
	'Please enter a city.';
$lang['en_US']['CheckoutPage']['PLEASEENTERACOUNTRY'] = 
	'Please enter a country.';
$lang['en_US']['CheckoutPage']['Region'] = 
	'Region';
$lang['en_US']['CheckoutPage']['sameaddress'] = 
	'to same address?';
$lang['en_US']['CheckoutPage']['Shipping Address'] = 
	'Shipping Address';
$lang['en_US']['CheckoutPage']['Email'] = 
	'Email';
$lang['en_US']['CheckoutPage']['PERSONALDETAILS'] = 
	'Personal Details';
$lang['en_US']['CheckoutPage']['Phone'] = 
	'Phone';
$lang['en_US']['CheckoutPage']['PASSWORD'] = 
	'Password';
$lang['en_US']['CheckoutPage']['PASSWORDNOTE'] = 
	'<p class="alert alert-info">
							<strong class="alert-heading">NOTE:</strong>
							Please choose a password, so you can login and check your order history in the future. <br /><br />
							If you are already a member please <a href="Security/login?BackURL=$link">log in</a>.
						</p>';
$lang['en_US']['CheckoutPage']['NOTESABOUTTHISORDER'] = 
	'Notes about this order';
$lang['en_US']['CheckoutPage']['SELECTPAYMENTMETHOD'] = 
	'Please select a payment method.';
$lang['en_US']['CheckoutPage']['NOTAVALIDPAYMENTMETHOD'] = 
	'Sorry, that is not a valid payment method.';
$lang['en_US']['CheckoutPage']['GOBACKTRYAGAIN'] = 
	'Please go back and try again.';
$lang['en_US']['CheckoutPage']['MEMBERALREADYEXISTS'] = 
	'Sorry, a member already exists with that email address. If this is your email address, please log in first before placing your order.';

// Output for class or file: CheckoutPage. Please enter your email address
$lang['en_US']['CheckoutPage. Please enter your email address'][''] = 
	'Please enter your email address.';

// Output for class or file: Customer
$lang['en_US']['Customer']['CANTDELETECUSTOMER'] = 
	'Can\'t not delete this customer because he have orders on the system.';
$lang['en_US']['Customer']['ADDRESS'] = 
	'Address';
$lang['en_US']['Customer']['CITY'] = 
	'City';
$lang['en_US']['Customer']['STATE'] = 
	'State';
$lang['en_US']['Customer']['POSTALCODE'] = 
	'Postal Code';
$lang['en_US']['Customer']['COUNTRY'] = 
	'Country';

// Output for class or file: Form
$lang['en_US']['Form']['VALIDATIONFAILED'] = 
	'Validation failed';
$lang['en_US']['Form']['VARIATIONS_REQUIRED'] = 
	'This product requires options before it can be added to the cart.';
$lang['en_US']['Form']['STOCK_LEVEL'] = 
	'Sorry, this product is out of stock';
$lang['en_US']['Form']['STOCK_LEVEL_MORE_THAN_QUANTITY'] = 
	'The quantity is greater than available stock for this product.';
$lang['en_US']['Form']['ITEM_IS_NOT_IN_ORDER'] = 
	'This product is not in the Cart.';
$lang['en_US']['Form']['ITEM_QUANTITY_INCORRECT'] = 
	'The quantity must be at least one (1).';
$lang['en_US']['Form']['ORDER_IS_NOT_VALID'] = 
	'Your cart seems to be empty, please add an item from the shop';
$lang['en_US']['Form']['STOCK_LEVEL_NOT_NUMERIC'] = 
	'This stock value is not a number.';
$lang['en_US']['Form']['VARIATION_PRICE_NOT_EXISTS'] = 
	'There is a problem with the variation price.';
$lang['en_US']['Form']['VARIATION_PRICE_NEGATIVE'] = 
	'This variation price is negative.';
$lang['en_US']['Form']['FLAT_FEE_SHIPPING_NOT_EXISTS'] = 
	'This shipping option is no longer available sorry';
$lang['en_US']['Form']['SHIPPING_ADDRESS_COUNTRY_NOT_EXISTS'] = 
	'Please select a country for the shipping address';
$lang['en_US']['Form']['FLAT_FEE_SHIPPING_OPTION_NOT_EXISTS'] = 
	'This shipping option is no longer available sorry';
$lang['en_US']['Form']['FLAT_FEE_SHIPPING_COUNTRY_NOT_MATCH'] = 
	'This shipping option is no longer available for the shipping country you have selected sorry';

// Output for class or file: StockFieldp
$lang['en_US']['StockFieldp'][''] = 
	'Stock : %s are currently in shopping carts, %s in orders that have not been dispatched.';

// Output for class or file: StockField
$lang['en_US']['StockField']['UNLIMITED'] = 
	'Unlimited';
$lang['en_US']['StockField']['SPECIFYSTOCK'] = 
	'Specify Stock';

// Output for class or file: ComplexTableField
$lang['en_US']['ComplexTableField']['CLOSEPOPUP'] = 
	'Close Popup';
$lang['en_US']['ComplexTableField']['SUCCESSADD'] = 
	'Added %s %s %s';
$lang['en_US']['ComplexTableField']['SUCCESSEDIT'] = 
	'Saved %s %s %s';

// Output for class or file: FlatFeeShippingRate
$lang['en_US']['FlatFeeShippingRate']['LABEL'] = 
	'Label';
$lang['en_US']['FlatFeeShippingRate']['DESCRIPTION'] = 
	'Description';
$lang['en_US']['FlatFeeShippingRate']['AMOUNT'] = 
	'Amount';
$lang['en_US']['FlatFeeShippingRate']['COUNTRY'] = 
	'Country';
$lang['en_US']['FlatFeeShippingRate']['NOCOUNTRYSET'] = 
	'No Country Set';

// Output for class or file: FlatFeeTaxRate
$lang['en_US']['FlatFeeTaxRate']['LABEL'] = 
	'Label';
$lang['en_US']['FlatFeeTaxRate']['DESCRIPTION'] = 
	'Description';
$lang['en_US']['FlatFeeTaxRate']['AMOUNT'] = 
	'Amount';
$lang['en_US']['FlatFeeTaxRate']['COUNTRY'] = 
	'Country';
$lang['en_US']['FlatFeeTaxRate']['TAXRATEASAPERCENTAGE'] = 
	'Tax rate as a percentage';

// Output for class or file: Order_NotificationEmail
$lang['en_US']['Order_NotificationEmail']['ORDER'] = 
	'Order';
$lang['en_US']['Order_NotificationEmail']['LOGIN'] = 
	'Log in to the CMS to manage this order';

// Output for class or file: Order_ReceiptEmail
$lang['en_US']['Order_ReceiptEmail']['HI'] = 
	'Hi';
$lang['en_US']['Order_ReceiptEmail']['ORDER'] = 
	'Order';
$lang['en_US']['Order_ReceiptEmail']['VIEWTHISORDER'] = 
	'View this order';
$lang['en_US']['Order_ReceiptEmail']['PAYMENTNOTICE'] = 
	'Please note that orders will not be shipped until payment has been successfully processed.';

// Output for class or file: CartForm
$lang['en_US']['CartForm']['PRODUCT'] = 
	'Product';
$lang['en_US']['CartForm']['OPTIONS'] = 
	'Options';
$lang['en_US']['CartForm']['UNITPRICE'] = 
	'Unit Price';
$lang['en_US']['CartForm']['QUANTITY'] = 
	'Quantity';
$lang['en_US']['CartForm']['SUBTOTAL'] = 
	'Sub Total';
$lang['en_US']['CartForm']['NOTE'] = 
	'Note:';
$lang['en_US']['CartForm']['NOITEMSINYOURCART'] = 
	'There are no items in your cart.';
$lang['en_US']['CartForm']['POWEREDBY'] = 
	'powered by';

// Output for class or file: CheckoutForm
$lang['en_US']['CheckoutForm']['YOURORDER'] = 
	'Your Order';

// Output for class or file: CheckoutFormOrder
$lang['en_US']['CheckoutFormOrder']['PRODUCT'] = 
	'Product';
$lang['en_US']['CheckoutFormOrder']['OPTIONS'] = 
	'Options';
$lang['en_US']['CheckoutFormOrder']['UNITPRICE'] = 
	'Unit Price';
$lang['en_US']['CheckoutFormOrder']['QUANTITY'] = 
	'Quantity';
$lang['en_US']['CheckoutFormOrder']['SUBTOTAL'] = 
	'Sub Total';
$lang['en_US']['CheckoutFormOrder']['NOITEMSINYOURCART'] = 
	'There are no items in your cart.';
$lang['en_US']['CheckoutFormOrder']['TOTAL'] = 
	'Total';

// Output for class or file: Order
$lang['en_US']['Order']['PRODUCT'] = 
	'Product';
$lang['en_US']['Order']['OPTIONS'] = 
	'Options';
$lang['en_US']['Order']['UNITPRICE'] = 
	'Unit Price';
$lang['en_US']['Order']['QUANTITY'] = 
	'Quantity';
$lang['en_US']['Order']['SUBTOTAL'] = 
	'Sub Total';
$lang['en_US']['Order']['TOTAL'] = 
	'Total';

// Output for class or file: OrderAddresses
$lang['en_US']['OrderAddresses']['BILLINGADDRESS'] = 
	'Billing Address';
$lang['en_US']['OrderAddresses']['SHIPPINGADDRESS'] = 
	'Shipping Address';

// Output for class or file: OrderAdmin
$lang['en_US']['OrderAdmin']['ORDER'] = 
	'Order';

// Output for class or file: OrderNotes
$lang['en_US']['OrderNotes']['NOTES'] = 
	'Notes';

// Output for class or file: OrderPayments
$lang['en_US']['OrderPayments']['PAYMENT'] = 
	'Payment';
$lang['en_US']['OrderPayments']['DATE'] = 
	'Date';
$lang['en_US']['OrderPayments']['AMOUNT'] = 
	'Amount';
$lang['en_US']['OrderPayments']['PAYMENTSTATUS'] = 
	'Payment Status';
$lang['en_US']['OrderPayments']['TOTALOUTSTANDING'] = 
	'Total outstanding';

// Output for class or file: Pagination
$lang['en_US']['Pagination']['PREV'] = 
	'Prev';
$lang['en_US']['Pagination']['NEXT'] = 
	'Next';

// Output for class or file: Products
$lang['en_US']['Products']['NOPRODUCTSTODISPLAY'] = 
	'Sorry, there are no products to display in this category. We will be adding more products shortly, come back soon!';

// Output for class or file: ShopAdmin_right
$lang['en_US']['ShopAdmin_right']['LOADING'] = 
	'Loading...';

// Output for class or file: AccountPage_order
$lang['en_US']['AccountPage_order']['WARNING'] = 
	'Warning!';
